In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
data=pd.read_csv(r"C:\Users\Tejes\Downloads\mushrooms.csv")
data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [12]:
data.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [13]:
data.drop(['cap-shape','cap-surface','veil-type','ring-type','population'],axis=1,inplace=True)

In [15]:
data=pd.get_dummies(data)
data.head()

class_e  class_p  cap-color_b  cap-color_c  cap-color_e  cap-color_g  \
0        0        1            0            0            0            0   
1        1        0            0            0            0            0   
2        1        0            0            0            0            0   
3        0        1            0            0            0            0   
4        1        0            0            0            0            1   

   cap-color_n  cap-color_p  cap-color_r  cap-color_u  ...  \
0            1            0            0            0  ...   
1            0            0            0            0  ...   
2            0            0            0            0  ...   
3            0            0            0            0  ...   
4            0            0            0            0  ...   

   spore-print-color_u  spore-print-color_w  spore-print-color_y  habitat_d  \
0                    0                    0                    0          0   
1                    0                    0                    0          0   
2                    0                    0                    0          0   
3                    0                    0                    0          0   
4                    0                    0                    0          0   

   habitat_g  habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          0          0          1          0  
1          1          0          0          0          0          0  
2          0          0          1          0          0          0  
3          0          0          0          0          1          0  
4          1          0          0          0          0          0  

[5 rows x 97 columns]

In [29]:
y=data['class_e']
x=data.drop(['class_e'],axis=1)

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [27]:
!pip install naive-bayes

In [31]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

In [33]:
y_pred=nb.predict(x_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
acc=accuracy_score(y_test,y_pred)
cm

array([[782,   0],
       [  0, 843]], dtype=int64)

In [39]:
from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB()
bnb.fit(x_train,y_train)

BernoulliNB()

In [40]:
y_pred=bnb.predict(x_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [42]:
cm=confusion_matrix(y_test,y_test)
accuracy_score(y_test,y_pred)
cm

array([[782,   0],
       [  0, 843]], dtype=int64)